### ISSUE TITLE
Custom authentication message

### ISSUE THREAD

**Issue by f-batiri** [FJNR-inc/dry-rest-permissions#27]
Thanks for such a great framework. Works very well so far.
Is there anyway to add custom message explaining why use does not have permission to access an action or object? (meaning change default "You do not have permission to perform this action.")

**Comment by RignonNoel** [comment]
Seems to be a great idea, and I share your frustration on this point.
If somebody is motivated to propose an architecture we could try to implement that.

**Comment by mjaquiery** [comment]
I'd suggest that if a test returns a string it gets interpreted as a failure and the string is used as the exception description.

**Comment by mjaquiery** [comment]
This should now be closed by #30 :)
